### ISSUE TITLE
Why did you use euclidean norm in penalization?

### ISSUE THREAD

**Issue by flrngel** [Diego999/SelfSent#1]
Seems normalization here did not use Frobenius norm as paper.

https://github.com/Diego999/SelfSent/blob/master/src/self_sent.py#L73

Do you have any comments about using Euclidean norm from here?

It seems to be `ord='fro'`

**Comment by diegoantognini** [comment]
Hi,

From the definition ![image](https://user-images.githubusercontent.com/1092464/32795502-268c2e8c-c96c-11e7-9dd2-127546a21756.png), this is similar to euclidian distance when treating all values in the matrix as a single vector. As TF's doc says: Default is 'euclidean' which is equivalent to Frobenius norm if tensor is a matrix and equivalent to 2-norm for vectors.

**Comment by flrngel** [comment]
I understand. Thanks a lot!
